package jsp2;

// default package
// Generated 10-jun-2015 14:47:24 by Hibernate Tools 4.0.0

/**
 * EmpDetailsView generated by hbm2java
 */
public class EmpDetailsView implements java.io.Serializable {

	private EmpDetailsViewId id;

	public EmpDetailsView() {
	}

	public EmpDetailsView(EmpDetailsViewId id) {
		this.id = id;
	}

	public EmpDetailsViewId getId() {
		return this.id;
	}

	public void setId(EmpDetailsViewId id) {
		this.id = id;
	}

}
